# Site settings
title: MyAnata Blog
SEOTitle: 僕光的博客 | MyAnata Blog
header-img: "https://s2.loli.net/2024/10/13/cBFweRAzLEqOoaK.jpg"
email: leekunheng88@gmail.com
description: "这可以是我的日记、随笔以及一些想法的分享。Let's think."
keyword: "EGG, MyAnata Blog, 僕光的博客, lee,  iOS, Apple, iPhone,ipad"
url: "http://https://kobeebry-ant.github.io/"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/KobeeBry-ant/KobeeBry-ant.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "No description is the best description."
sidebar-avatar: https://s2.loli.net/2024/10/13/TBzSWFNefKomPxp.jpg    # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
#zhihu_username:     qiubaiying
#github_username:    qiubaiying
#facebook_username:  baiying.qiu.7
#jianshu_username:   e71990ada2fd
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



